import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import { Inter } from "next/font/google";
import Providers from "./_components/Providers";
import { authOptions } from "./api/auth/[...nextauth]/route";
import "./globals.css";
import NextTopLoader from 'nextjs-toploader'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextTopLoader />
        <Providers>
          {/* {session && <NavigationBar name={session?.user?.name} username={session?.user?.username} role={session?.user?.role}/>} */}
          {children}
        </Providers>
      </body>
    </html>
  );
}
